version: '3.1'

services:
  postgres:
    image: postgres:14
    container_name: postgres-db
    restart: always
    ports:
      - "1488:5432"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: qwe

  app:
    image: nikitkamzgb/test-to
    container_name: test-to-app
    restart: always
    depends_on:
      - postgres
    ports:
      - "1111:1111"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/postgres?autoreconnect=true
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: qwe
      SPRING_JPA_HIBERNATE_DDL_AUTO: update